version: "3"

services:
  app:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "8000:8888"
    volumes:
      #mount all the code in app directory in local to app directory of conatiner
      - ./chatbot/:/chatbot
    working_dir: /chatbot
    command: > 
      sh -c "conda update -n base -c defaults conda && 
      jupyter notebook  --ip='*' --port=8888 --no-browser --allow-root"